version: '3.9'

services:
  redis:
    hostname: my-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis